server:
  port: ${PORT:8085}

spring:
  application:
    name: PAYMENT-SERVICE

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/canteen_db_new?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:admin}
#    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}

razorpay:
  key-id: ${ RAZORPAY_ID:rzp_test_TKsNh0krjimjTG }
  key-secret: ${RAZORPAY_SECRET:Vqd0FQ6pGXpT4RxZG3LBC7lr}
  webhook-secret: ${ WEBHOOK_SECRET }