server:
  port: ${PORT}

spring:
  application:
    name: PAYMENT-SERVICE

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
#    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

razorpay:
  key-id: ${ RAZORPAY_ID }
  key-secret: ${RAZORPAY_SECRET}
  webhook-secret: ${ WEBHOOK_SECRET }
