server:
  port: ${PORT}

spring:
  application:
    name: NOTIFICATION-SERVICE
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_ID:rajput.prince.dev@gmail.com}
    password: ${EMAIL_PASSWORD:zzoi atrh gstp zjcp}

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
